### ISSUE TITLE
API de lógica del juego - Implementación de la fase de refuerzo

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#11]
- [x] Implementación de la baraja
- [x] Cambio de cartas
- [x] Asignación inicial de tropas en función de territorios y continentes ocupados
- [x] Paso a fase de ataque
- [x] Testing de la baraja
- [x] Testing de integración de la fase en el juego
- [x] Decidir como gestionar cambios con varias bonificaciones de territorios a la vez

**Comment by Guilleuz** [comment]
Implementación básica de la baraja en a4f09053ade428739d5f9247d328b01c5fdd290f

**Comment by Guilleuz** [comment]
Funciones para el cambio de cartas y recibir cartas implementadas en 4bdd1f95944622c01b7309d76b845b5e6f6b4016

**Comment by Guilleuz** [comment]
Test unitario de la baraja y corrección de las funciones anteriores en c34a409937db60dc2054ac2e7ba2a4b75568bf31

**Comment by Guilleuz** [comment]
Asignación de tropas implementada en 1df23424cbc3a92b5e6ef21c0dd7c3906dab0108, testeada en 18d168403d93c205c3c094936e8a595c5cbeb9da

**Comment by Guilleuz** [comment]
Implementado el cambio de fase en 56179c77ae91b951847fdfa8aa449354e427ed6a, testeado (junto con asignación inicial de tropas) en el test de integración de la fase de refuerzo 425e97cfd68fd8ad9d0bf77dc451987d74d67948

**Comment by Guilleuz** [comment]
Se ha decidido asignar dos tropas a cada territorio que reciba una bonificación durante el cambio de carta.

**Comment by Guilleuz** [comment]
Implementación de la bonificación por múltiples territorios en 7ea21b77896b86f24e417bb9861060630f236213
