### ISSUE TITLE
API de lógica del juego - Implementacion de la fase de ataque

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#12]
- [x] Implementar función para el ataque
- [x] Implementar llamada API para el ataque
- [x] Implementar función para la ocupación de un territorio desocupado
- [x] Implementar llamada API para la ocupación de un territorio desocupado
- [x] Implementar derrota de un jugador
- [x] Modificar estado para tener en cuenta la última tirada
- [x] Añadir restricciones al ataque y al cambio de fase para que no se puedan realizar si hay cartas por cambiar o territorios por ocupar
- [x] Test unitario de la función de ataque
- [x] Test unitario de la función de ocupación
- [x] Documentar funciones
- [x] Test de integración de ambas funcionalidades

**Comment by Guilleuz** [comment]
Implementación de la función de ataque en d91171bd9291ad8c19a46fee3f146342edb6b569.
Testing unitario de la misma en bf7d89bb961fd50ae90e21ae6749f12eb9d8d985.

**Comment by Guilleuz** [comment]
Implementación de la eliminación de un usuario en 71f8aa49e5c1c74832775a9d94a402f8c9e923ef.

**Comment by Guilleuz** [comment]
Implementada  y probada función de ocupación en 69d7662eed65572e3bcd74e5efcf0d0f83050dd9.

**Comment by Guilleuz** [comment]
Llamadas a la API y documentación en 9f357c5fdbd3fd59d7b8c18780ee3f9d19439c07.

**Comment by Guilleuz** [comment]
Test de integración de la fase de ataque en 623eb99fed004a093c7609201efc19869aaf58d6.
