### ISSUE TITLE
API de tienda

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#14]
- [x] Consultar objetos disponibles en la tienda
- [x] Realizar una compra en la tienda
- [x] Consultar objetos adquiridos por un jugador

**Comment by Guilleuz** [comment]
Consultar tienda en 7e9327756e23fea7adcc2659546f0f97f58a80cd.
Consultar colección en f798c231b2fe46457bca1e3bb7384586c2f1b7e8.
Compra de un objeto y pruebas en ce6c21c417324622f9fa35a56e7df32fd63995d7.
