### ISSUE TITLE
API de personalización de perfiles de usuario

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#15]
- [x] Personalización de biografía
- [x] Personalización de dados
- [x] Personalización de fichas

**Comment by Guilleuz** [comment]
Personalización de biografía en 97a0db10ef905e37651d27e375f9a42a42ea9100.
Modificación de dados y fichas en 392794d31016d2639d424fdf2e831747a08ffe98.
Generalización de las funciones de modificar dados y fichas en una sola + pruebas en 8652f2b5b45d4bd96f5574d840d482835af1261c.
