### ISSUE TITLE
Implementación del final del juego

### ISSUE THREAD

**Issue by Guilleuz** [UNIZAR-30226-2022-01/proyecto_software_backend#19]
- [x] Hacer mensaje de jugador eliminado
- [x] Hacer notificación de fin de partida
- [x] Borrar participaciones al finalizar partida o ser eliminado
- [x] Eliminación de partida de BD y cache
- [x] Contabilizar partidas como ganadas o perdidas
- [x] Otorgar puntos

**Comment by Sondeluz** [comment]
Implementado en b64b199f644379187e45be5102a61c879458ba9e
