### ISSUE TITLE
API de búsqueda y configuración de partidas

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#3]
- [x] Búsqueda de partidas
- [x] Creación de partidas
- [x] Documentar búsqueda de partidas
- [x] Documentar creación de partidas
- [x] Unirse a partidas
- [x] Dejar partidas : Samuel

**Comment by Sondeluz** [comment]
Búsqueda implementada.

**Comment by Guilleuz** [comment]
Creación implementada 9184ca11abab2cc1b33453e63748400953053b3a

**Comment by Sondeluz** [comment]
Por documentar códigos HTTP y JSON de respuesta

**Comment by Sondeluz** [comment]
Dejar partidas implementado en fac91232d93abfaf7171031d20e6ff6d2167aee0
