### ISSUE TITLE
Versión parcial de la API de lógica de juego

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#5]
- [x] Crear autómata de una partida
- [x] Definir acciones a realizar
- [x] Definir el estado de una partida
- [x] Definir endpoints de API para consultar cada elemento de la partida
- [x] Definir endpoints de API para acciones de la partida
- [ ] Realizar una implementación parcial de los endpoints

**Comment by Guilleuz** [comment]
Autómata creado, definición de acciones y estado de la partida
https://excalidraw.com/#room=c52a649678f5e8464b01,hUkCwOZbQMPnfNvQ4igtfw

**Comment by Sondeluz** [comment]
Tareas:

- [ ] Implementar lista de acciones: Guillermo y Samuel
- [ ] Implementar estado: Guillermo y Samuel
- [ ] Obtener estado de lobby y endpoints auxiliares
- [ ] Obtener estado de la partida y obtener lista de acciones de la partida, de momento lo mismo: Guillermo y Samuel
- [ ] Implementación del principio de la partida (rellenar territorios, reforzar territorios y poblar lista de acciones)
- [ ] Implementación de la fase de refuerzo
- [ ] Implementacion de la fase de ataque
- [ ] Implementación de la fase de fortificar

**Comment by Guilleuz** [comment]
Estado de lobby implementado en c695f8860e5ad6e1347c2ab84231e900d4084863

**Comment by Sondeluz** [comment]
Implementación restante tras el hito:

- [ ] Implementacion de la fase de ataque: Guillermo
- [ ] Implementación de la fase de fortificar: Samuel

A continuar en https://github.com/UNIZAR-30226-2022-01/proyecto_software_backend/issues/18
