### ISSUE TITLE
APIs auxiliares

### ISSUE THREAD

**Issue by Sondeluz** [UNIZAR-30226-2022-01/proyecto_software_backend#9]
APIs no relacionadas con ningún aspecto de juego en general

- [x] Listar amigos 
- [x] Obtener información de perfil de usuario
- [x] Obtener usuarios que coincidan con una búsqueda por nombre

**Comment by Guilleuz** [comment]
Listar amigos implementada en 6953be9e2d20d3bcfdad0784e2942240a2a9afc6. 
Obtener perfil y usuarios similares implementadas en 6edbec54e8667e07426f1258ff0c177e7571b14d.
